name = "SCTransform"
uuid = "f56ea72b-d1ea-403e-9c0c-95d94e8a8532"
authors = ["Rasmus Henningsson <rasmus.henningsson@med.lu.se>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
